/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CareerRouteImport } from './routes/career'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DimisiAdminRouteImport } from './routes/dimisi-admin'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ReviewSlugRouteImport } from './routes/review.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ServicesAiRouteImport } from './routes/services.ai'
import { Route as ServicesApiRouteImport } from './routes/services.api'
import { Route as ServicesAutomationRouteImport } from './routes/services.automation'
import { Route as ServicesCloudRouteImport } from './routes/services.cloud'
import { Route as ServicesEnterpriseRouteImport } from './routes/services.enterprise'
import { Route as ServicesMobileAppRouteImport } from './routes/services.mobile-app'
import { Route as ServicesUiUxRouteImport } from './routes/services.ui-ux'
import { Route as ServicesWebDevelopmentRouteImport } from './routes/services.web-development'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DimisiAdminRoute = DimisiAdminRouteImport.update({
  id: '/dimisi-admin',
  path: '/dimisi-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ReviewSlugRoute = ReviewSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ReviewRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAiRoute = ServicesAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesApiRoute = ServicesApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAutomationRoute = ServicesAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCloudRoute = ServicesCloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesEnterpriseRoute = ServicesEnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesMobileAppRoute = ServicesMobileAppRouteImport.update({
  id: '/mobile-app',
  path: '/mobile-app',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesUiUxRoute = ServicesUiUxRouteImport.update({
  id: '/ui-ux',
  path: '/ui-ux',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesWebDevelopmentRoute = ServicesWebDevelopmentRouteImport.update({
  id: '/web-development',
  path: '/web-development',
  getParentRoute: () => ServicesRoute,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/dimisi-admin': typeof DimisiAdminRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/review': typeof ReviewRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/review/$slug': typeof ReviewSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/ai': typeof ServicesAiRoute
  '/services/api': typeof ServicesApiRoute
  '/services/automation': typeof ServicesAutomationRoute
  '/services/cloud': typeof ServicesCloudRoute
  '/services/enterprise': typeof ServicesEnterpriseRoute
  '/services/mobile-app': typeof ServicesMobileAppRoute
  '/services/ui-ux': typeof ServicesUiUxRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
  '/work/$slug': typeof WorkSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/dimisi-admin': typeof DimisiAdminRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/review': typeof ReviewRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/review/$slug': typeof ReviewSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/ai': typeof ServicesAiRoute
  '/services/api': typeof ServicesApiRoute
  '/services/automation': typeof ServicesAutomationRoute
  '/services/cloud': typeof ServicesCloudRoute
  '/services/enterprise': typeof ServicesEnterpriseRoute
  '/services/mobile-app': typeof ServicesMobileAppRoute
  '/services/ui-ux': typeof ServicesUiUxRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
  '/work/$slug': typeof WorkSlugRoute
  '/services': typeof ServicesIndexRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/dimisi-admin': typeof DimisiAdminRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/review': typeof ReviewRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/review/$slug': typeof ReviewSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/ai': typeof ServicesAiRoute
  '/services/api': typeof ServicesApiRoute
  '/services/automation': typeof ServicesAutomationRoute
  '/services/cloud': typeof ServicesCloudRoute
  '/services/enterprise': typeof ServicesEnterpriseRoute
  '/services/mobile-app': typeof ServicesMobileAppRoute
  '/services/ui-ux': typeof ServicesUiUxRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
  '/work/$slug': typeof WorkSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/blog'
    | '/career'
    | '/contact'
    | '/dimisi-admin'
    | '/events'
    | '/gallery'
    | '/privacy'
    | '/products'
    | '/review'
    | '/reviews'
    | '/services'
    | '/team'
    | '/terms'
    | '/blog/$slug'
    | '/review/$slug'
    | '/services/$slug'
    | '/services/ai'
    | '/services/api'
    | '/services/automation'
    | '/services/cloud'
    | '/services/enterprise'
    | '/services/mobile-app'
    | '/services/ui-ux'
    | '/services/web-development'
    | '/work/$slug'
    | '/services/'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/blog'
    | '/career'
    | '/contact'
    | '/dimisi-admin'
    | '/events'
    | '/gallery'
    | '/privacy'
    | '/products'
    | '/review'
    | '/reviews'
    | '/team'
    | '/terms'
    | '/blog/$slug'
    | '/review/$slug'
    | '/services/$slug'
    | '/services/ai'
    | '/services/api'
    | '/services/automation'
    | '/services/cloud'
    | '/services/enterprise'
    | '/services/mobile-app'
    | '/services/ui-ux'
    | '/services/web-development'
    | '/work/$slug'
    | '/services'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/blog'
    | '/career'
    | '/contact'
    | '/dimisi-admin'
    | '/events'
    | '/gallery'
    | '/privacy'
    | '/products'
    | '/review'
    | '/reviews'
    | '/services'
    | '/team'
    | '/terms'
    | '/blog/$slug'
    | '/review/$slug'
    | '/services/$slug'
    | '/services/ai'
    | '/services/api'
    | '/services/automation'
    | '/services/cloud'
    | '/services/enterprise'
    | '/services/mobile-app'
    | '/services/ui-ux'
    | '/services/web-development'
    | '/work/$slug'
    | '/services/'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CareerRoute: typeof CareerRoute
  ContactRoute: typeof ContactRoute
  DimisiAdminRoute: typeof DimisiAdminRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  ReviewRoute: typeof ReviewRouteWithChildren
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  WorkSlugRoute: typeof WorkSlugRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dimisi-admin': {
      id: '/dimisi-admin'
      path: '/dimisi-admin'
      fullPath: '/dimisi-admin'
      preLoaderRoute: typeof DimisiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/review/$slug': {
      id: '/review/$slug'
      path: '/$slug'
      fullPath: '/review/$slug'
      preLoaderRoute: typeof ReviewSlugRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ai': {
      id: '/services/ai'
      path: '/ai'
      fullPath: '/services/ai'
      preLoaderRoute: typeof ServicesAiRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/api': {
      id: '/services/api'
      path: '/api'
      fullPath: '/services/api'
      preLoaderRoute: typeof ServicesApiRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/automation': {
      id: '/services/automation'
      path: '/automation'
      fullPath: '/services/automation'
      preLoaderRoute: typeof ServicesAutomationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cloud': {
      id: '/services/cloud'
      path: '/cloud'
      fullPath: '/services/cloud'
      preLoaderRoute: typeof ServicesCloudRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/enterprise': {
      id: '/services/enterprise'
      path: '/enterprise'
      fullPath: '/services/enterprise'
      preLoaderRoute: typeof ServicesEnterpriseRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/mobile-app': {
      id: '/services/mobile-app'
      path: '/mobile-app'
      fullPath: '/services/mobile-app'
      preLoaderRoute: typeof ServicesMobileAppRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ui-ux': {
      id: '/services/ui-ux'
      path: '/ui-ux'
      fullPath: '/services/ui-ux'
      preLoaderRoute: typeof ServicesUiUxRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/web-development': {
      id: '/services/web-development'
      path: '/web-development'
      fullPath: '/services/web-development'
      preLoaderRoute: typeof ServicesWebDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ReviewRouteChildren {
  ReviewSlugRoute: typeof ReviewSlugRoute
}

const ReviewRouteChildren: ReviewRouteChildren = {
  ReviewSlugRoute: ReviewSlugRoute,
}

const ReviewRouteWithChildren =
  ReviewRoute._addFileChildren(ReviewRouteChildren)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesAiRoute: typeof ServicesAiRoute
  ServicesApiRoute: typeof ServicesApiRoute
  ServicesAutomationRoute: typeof ServicesAutomationRoute
  ServicesCloudRoute: typeof ServicesCloudRoute
  ServicesEnterpriseRoute: typeof ServicesEnterpriseRoute
  ServicesMobileAppRoute: typeof ServicesMobileAppRoute
  ServicesUiUxRoute: typeof ServicesUiUxRoute
  ServicesWebDevelopmentRoute: typeof ServicesWebDevelopmentRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesAiRoute: ServicesAiRoute,
  ServicesApiRoute: ServicesApiRoute,
  ServicesAutomationRoute: ServicesAutomationRoute,
  ServicesCloudRoute: ServicesCloudRoute,
  ServicesEnterpriseRoute: ServicesEnterpriseRoute,
  ServicesMobileAppRoute: ServicesMobileAppRoute,
  ServicesUiUxRoute: ServicesUiUxRoute,
  ServicesWebDevelopmentRoute: ServicesWebDevelopmentRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CareerRoute: CareerRoute,
  ContactRoute: ContactRoute,
  DimisiAdminRoute: DimisiAdminRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  ReviewRoute: ReviewRouteWithChildren,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  WorkSlugRoute: WorkSlugRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
